#!/usr/bin/env node

// file from https://blog.davehylands.com/capturing-usb-serial-using-wireshark/

'use strict';

// Since this is just an example, we'll just read the entire JSON
// file in.
// get this file using Wireshark
// Export the data using: File->Export Packet Dissections->As JSON… choosing “All Packets” and “Displayed”.
const json = require('/home/sru/playground/off7.json');

const isFTDI = true;

for (const packet of json) {
  const layer = packet._source.layers;
  const frameNum = layer.frame['frame.number'];
  const timeStamp = layer.frame['frame.time_relative'].slice(0, -6);
  const usb = layer.usb;
  let data = layer['usb.capdata'].replace(/:/g, '');

  const read = usb['usb.dst'] === 'host';
  if (read) {
    if (isFTDI) {
      // Remove the FTDI status bytes
      data = data.slice(4);
    }
    if (data.length == 0) {
      continue;
    }
  }

  let label = `     ${timeStamp}`.slice(-9);
  label += `     ${frameNum}`.slice(-6);
  label += read ? ' R:' : ' W:';

  console.log(label, Buffer.from(data, 'hex'));
}
