name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'usbman'
            platform:  'ubuntu-22.04-amd64'
            os: 'ubuntu-22.04'
          - name: 'usbman'
            platform:  'ubuntu-24.04-amd64'
            os: 'ubuntu-24.04'
#          - name: 'usbman'
#            platform:  'macos-15-intel'
#            os: 'macos-15-intel'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: setup generic
        if: ${{ matrix.build.os != 'macos-15-intel' }}
        run: |
          pip3 install -r requirements.txt
          pipenv --python /bin/python3 install -d

      - name: setup macos
        if: ${{ matrix.build.os == 'macos-15-intel' }}
        run: |
          pip3 install --break-system-packages -r requirements.txt
          pipenv --python /usr/local/bin/python3 install -d

      - name: Add msbuild to PATH
        if: ${{ matrix.build.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Build
        run: |
          pipenv run ./package_usbman

      - name: Minimaly test
        run: |
          dist/usbman --help
          mv dist/usbman usbman-${{ matrix.build.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: usbman-${{ matrix.build.platform }}
          path: usbman-${{ matrix.build.platform }}

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build wheel
        run: |
          pip3 install -r requirements.txt
          pipenv --python /bin/python3 install -d
          pipenv run ./lint
          pipenv run ./buildit

      - name: Upload distributions
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pure-python
          path: dist/

      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: info  
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          ls -la
          ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            usbman-ubuntu-22.04-amd64/*
            usbman-ubuntu-24.04-amd64/*
            dist/*

  pypi-publish:
    runs-on: ubuntu-24.04
    needs:
      - release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
      #
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Retrieve release distributions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pure-python
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          packages-dir: dist/